### ISSUE TITLE
m2o doesn't seem to recognise new devices when they are added

### ISSUE THREAD

**Issue by llloret** [llloret/osmid#16]
This was reported by @samaaron on Mac

**Comment by llloret** [comment]
Works ok under Windows. Would be nice to have other reports under Mac.

**Comment by samaaron** [comment]
Great that it works under Windows :-)

Are you looking for other people confirming the issue on Mac - or are you looking for more information from Mac users with the issue?

**Comment by llloret** [comment]
Both, really. Just to check if the issue is a problem on all Macs, or just on some (or one ;)). And also to gather more information regardless of how widespread it is.

**Comment by llloret** [comment]
On my setup, it works on Linux too

**Comment by llloret** [comment]
What I have seen, is that on Windows, sometimes after the PC has gone to sleep, the detection is not 100% reliable, and the device cannot be opened. It happens to other SW as well (like midi-ox - which is a well known MIDI monitor), not just to osmid. So, I think it has to do more with drivers and OS interaction that a problem with osmid itself

**Comment by samaaron** [comment]
Perhaps @rbnpi will be able to take a look? Robin - do you have any external MIDI hardware?

**Comment by samaaron** [comment]
If it isn't a problem with osmid itself - I'll need to figure out how to be able to force an update from Sonic Pi without having to restart the app (as I currently have to do). The main issue with hard-resetting osmid in its current incarnation is that we'd lose the sticky IDs with duplicate MIDI ports :-(

**Comment by llloret** [comment]
The remark about possibly not being a problem with osmid itself, was mostly
for Windows, as I have seen it misbehave with other SW. About Mac, there
might be something wrong, that manifests on it...

**Comment by rbnpi** [comment]
At present I have used audio midi utility to connect to local machine (Mac) by its actual IP address (not 127.0.0.1) using port 5004. I find this needs to be set up before SP is started or I need to restart SP. I'll try a local USB midi interface and external synth this afternoon and see how that fares. Sleeping seems to clobber things, but not sure if that is the audio midi setup or SP without further investigation.

**Comment by rbnpi** [comment]
Had a play with an external keyboard with USB interface. osmid_m2o.log seemed quite happy when this was added and removed and re-added. Input was received and didn't seem to be any glitches. Also tried an external korg X5DR module connected via a UA25 midi-usb adapter and Sp seemed happy when this was selected and deselected in Audio Midi setup. Also both seemed OK following computer sleep and wakeup. Found that connection to SP worked fine when I used localhost with 127.0.0.1 and port 5004. It automatically also opened a port on the actual ip address of the computer. Audio Midi setup is a fairly inscrutable beast on the Mac and not very well documented!
Also had SP outputting happily to Logic Pro, MuseScore2 and external Korg simultaneously.

**Comment by llloret** [comment]
Hi, @rbnpi, great, thanks for the feedback, it is really useful. Just to make sure... this is on a Mac, right? Can you specify the OS version?

This is my experience on Linux and Windows which is what I can try.

@samaaron, it would be nice to find someone else that is having the same issues as you do, to try to find a pattern.

**Comment by rbnpi** [comment]
The build was on El Capitan 10.11.6 (not Sierra 10.12). I have built it on a virtual Sierra, but I can't test midi connectivity under that. ( will probably upgrade one of my two Macs to Sierra soon and try it properly there). Also I was NOT using the latest midi upgrade on SP as there is a missing function in it for which I have raised an issue https://github.com/samaaron/sonic-pi/issues/1559
I was instead using a build at commit #b56c5ef64e86d08271e0c72054aa10f3e0b97ee3 just before the latest midi commit

**Comment by samaaron** [comment]
@rbnpi did you boot Sonic Pi with *no* MIDI devices attached, then attach them and then try using them?

My observations are that if the MIDI device was attached when Sonic Pi first booted - then it will be detected and work and will also survive being unplugged and re-plugged. However, if a device *wasn't* attached at boot time, I can't get it to be recognised without rebooting Sonic Pi.

**Comment by rbnpi** [comment]
I have just experimented with this again. I disabled the audio midi connection, then started Sonic Pi and a midi player and then re-enabled the audio midi connection. SP would not transfer midi as per your experience. I quit and restarted SP and all was well again. I’ll investigate further with the logs but looks like I have the same observation you have. 

>

**Comment by rbnpi** [comment]
this thread would seem to be relevant to the issue
https://forum.juce.com/t/how-to-update-midi-device/14851

**Comment by llloret** [comment]
Thanks, @rbnpi, I'll have a look

**Comment by llloret** [comment]
Status update: Some weeks ago I asked @samaaron to test with the patch suggested in the link that @rbnpi sent, but there was no change of behaviour. Next step would be to ask again in the JUCE forums, I guess.

**Comment by llloret** [comment]
Update: some days ago I was able to create a simple reproducer for Mac. Need to communicate with the JUCE guys.

**Comment by samaaron** [comment]
I can confirm that this is still an issue on macOS.

**Comment by llloret** [comment]
I have just updated osmid master to JUCE 5.4.3 version. Can you check if that fixes the issue?

**Comment by rbnpi** [comment]
Still the same behaviour I'm afraid.
I notice the ./o2m --version is still giving 0.6.0 btw

**Comment by llloret** [comment]
Thanks for the update, @rbnpi, regarding the MIDI behaviour. I will see if I can work with the reproducer I prepared some time ago with the JUCE guys.
I have fixed the version now (0.6.5).

**Comment by llloret** [comment]
Have not heard new issues about this for a while. Closing and can be reopened if still an issue for some people.
