### ISSUE TITLE
OSC heartbeat uses nonstandard argument array type

### ISSUE THREAD

**Issue by samaaron** [llloret/osmid#21]
For the greatest compatibility with existing OSC servers it is best to stick to the plain OSC 1.0 argument types `i`, `s`, `f`, and `b`.

It might be best to send the heartbeat OSC message with just a list of strings - one for each device.

This issue affects both `m2o` and `o2m`.

**Comment by llloret** [comment]
Ok, I can change so that it sends this sort of OSC message:
i, s* (*: zero or more "s" args)

The integer specifies how many strings will follow (one per MIDI device), and then as many "s" args will follow.

Would that be ok?

**Comment by samaaron** [comment]
Would work very well for Sonic Pi - although in fact the initial integer count would be redundant as the Ruby library already presents the OSC args in an array. The OSC spec also already lets the server know how many args there are - so I would have hoped most OSC libs wouldn't need the initial count either

**Comment by llloret** [comment]
Ok, so it will have pairs of the form "i,s", since in the heartbeat message I am also sending the sticky id, as you requested in the past.
Is that ok?

**Comment by samaaron** [comment]
Ah, yes, good point :)

**Comment by llloret** [comment]
Fixed in master
