### ISSUE TITLE
template compilation errors on Raspbian for RPi

### ISSUE THREAD

**Issue by llloret** [llloret/osmid#24]

**Comment by llloret** [comment]
This might be a bug in the gcc compiler. 

Have a look at using the argument iterator interface instead of the stream interface. Look into `OscReceiveTest.cpp`, around line 71.

**Comment by llloret** [comment]
Tentative fix on branch `templates_not_working`. Asked @samaaron to give it a try and see if it works.

**Comment by llloret** [comment]
Fixed with #25

**Comment by samaaron** [comment]
Thanks so much :-)
