### ISSUE TITLE
m2o fails on Ubuntu 16.04 when used with Sonic Pi midi

### ISSUE THREAD

**Issue by jhw** [llloret/osmid#46]
I am using the latest osmid commit 72538fe596c404904f9a5b49cbc617121487f89 [Fri Jun 23 11:17:45 2017 +0100] and recent Sonic Pi commit a8cbd26c8022bb80a189fea025bf84edb546c17 [Sun Jun 25 09:52:59 2017 +0000]

When testing Sonic Pi midi I notice that the m2o process dies with a segmentation fault and no sound is heard from my Fluid softsynth (midi device)

If I try running m2o from the command line I get the following, ultimately returning a segmentation fault; looks to me like there is some kind of infinite loop with respect to midi port lookup

Many thanks

> $ ./build/m2o
> Found 6 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
> Found 9 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
> Found 12 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
> Found 15 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
>    (12): Juce Midi Output: Midi Through Port-0 (8)
>    (13): Juce Midi Output: Midi Through Port-0 (9)
>    (14): Juce Midi Output: Synth input port (3613:0) (5)
> Found 18 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
>    (12): Juce Midi Output: Midi Through Port-0 (8)
>    (13): Juce Midi Output: Midi Through Port-0 (9)
>    (14): Juce Midi Output: Synth input port (3613:0) (5)
>    (15): Juce Midi Output: Midi Through Port-0 (10)
>    (16): Juce Midi Output: Midi Through Port-0 (11)
>    (17): Juce Midi Output: Synth input port (3613:0) (6)
> Found 21 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
>    (12): Juce Midi Output: Midi Through Port-0 (8)
>    (13): Juce Midi Output: Midi Through Port-0 (9)
>    (14): Juce Midi Output: Synth input port (3613:0) (5)
>    (15): Juce Midi Output: Midi Through Port-0 (10)
>    (16): Juce Midi Output: Midi Through Port-0 (11)
>    (17): Juce Midi Output: Synth input port (3613:0) (6)
>    (18): Juce Midi Output: Midi Through Port-0 (12)
>    (19): Juce Midi Output: Midi Through Port-0 (13)
>    (20): Juce Midi Output: Synth input port (3613:0) (7)
> Found 24 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
>    (12): Juce Midi Output: Midi Through Port-0 (8)
>    (13): Juce Midi Output: Midi Through Port-0 (9)
>    (14): Juce Midi Output: Synth input port (3613:0) (5)
>    (15): Juce Midi Output: Midi Through Port-0 (10)
>    (16): Juce Midi Output: Midi Through Port-0 (11)
>    (17): Juce Midi Output: Synth input port (3613:0) (6)
>    (18): Juce Midi Output: Midi Through Port-0 (12)
>    (19): Juce Midi Output: Midi Through Port-0 (13)
>    (20): Juce Midi Output: Synth input port (3613:0) (7)
>    (21): Juce Midi Output: Midi Through Port-0 (14)
>    (22): Juce Midi Output: Midi Through Port-0 (15)
>    (23): Juce Midi Output: Synth input port (3613:0) (8)
> Found 27 MIDI inputs.
>    (0): Midi Through: Midi Through Port-0
>    (1): Juce Midi Output: Midi Through Port-0 (1)
>    (2): Juce Midi Output: Synth input port (3613:0) (1)
>    (3): Juce Midi Output: Midi Through Port-0 (2)
>    (4): Juce Midi Output: Midi Through Port-0 (3)
>    (5): Juce Midi Output: Synth input port (3613:0) (2)
>    (6): Juce Midi Output: Midi Through Port-0 (4)
>    (7): Juce Midi Output: Midi Through Port-0 (5)
>    (8): Juce Midi Output: Synth input port (3613:0) (3)
>    (9): Juce Midi Output: Midi Through Port-0 (6)
>    (10): Juce Midi Output: Midi Through Port-0 (7)
>    (11): Juce Midi Output: Synth input port (3613:0) (4)
>    (12): Juce Midi Output: Midi Through Port-0 (8)
>    (13): Juce Midi Output: Midi Through Port-0 (9)
>    (14): Juce Midi Output: Synth input port (3613:0) (5)
>    (15): Juce Midi Output: Midi Through Port-0 (10)
>    (16): Juce Midi Output: Midi Through Port-0 (11)
>    (17): Juce Midi Output: Synth input port (3613:0) (6)
>    (18): Juce Midi Output: Midi Through Port-0 (12)
>    (19): Juce Midi Output: Midi Through Port-0 (13)
>    (20): Juce Midi Output: Synth input port (3613:0) (7)
>    (21): Juce Midi Output: Midi Through Port-0 (14)
>    (22): Juce Midi Output: Midi Through Port-0 (15)
>    (23): Juce Midi Output: Synth input port (3613:0) (8)
>    (24): Juce Midi Output: Midi Through Port-0 (16)
>    (25): Juce Midi Output: Midi Through Port-0 (17)
>    (26): Juce Midi Output: Synth input port (3613:0) (9)
> Segmentation fault (core dumped)
> jhw@jhw-ThinkPad-X220:~/work/osmid$ 
> 
> 
> 
>

**Comment by jhw** [comment]
FWIW this sounds very much like the problem @rbnpi had with the Raspberry Pi a few days ago, but which got fixed. Is it possible Ubuntu needs a slightly different fix ?

**Comment by jhw** [comment]
No-one ? Closing :-(

**Comment by llloret** [comment]
Hi, not sure what problem Robin was having... can you point me to it and
I'll have a look.

Apologies for missing this. I am quite busy lately...
