### ISSUE TITLE
release for packaging

### ISSUE THREAD

**Issue by dvzrv** [llloret/osmid#48]
I'd like to package the latest sonic-pi for Arch Linux' [community] repository. Osmid is a dependency and therefore has to be packaged as well.

Can you please tag a release of this software, so I can package it?

**Comment by llloret** [comment]
Done, I have tagged as v0.6. Let me know how it goes.

**Comment by dvzrv** [comment]
Hmm, after

```
mkdir build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
make DESTDIR="${pkgdir}/" install
```

only `m2o` is installed to `/usr/bin` (in the `pkgdir`).

Also (in the case of Arch) libx11 is required to build and gcc-libs is required to run.

**Comment by llloret** [comment]
Let me check, I had never tried the install targets to be honest. Just the
build step...

**Comment by dvzrv** [comment]
Ah yeah. Here it is:
https://github.com/llloret/osmid/blob/master/CMakeLists.txt#L92

**Comment by llloret** [comment]
I have just added the missing rule to CMakelists.txt. I will retag as 0.6.1.

**Comment by dvzrv** [comment]
@llloret thanks! Try to keep the tag naming consistent (without `v` is fine, but with is okay too, as long as it stays the same).

**Comment by llloret** [comment]
Yes, sorry, v0.6.1 is what I meant. It should be ready now.

**Comment by dvzrv** [comment]
no worries. Pushed osmid to [community-testing], so I can get on with sonic-pi later on today.
Thanks for the quick reply! :)
