### ISSUE TITLE
o2m raw messages sending to all devices even when a specific device is given

### ISSUE THREAD

**Issue by PLu55** [llloret/osmid#51]
o2m raw messages sending to all devices even when a specific device is given

```/Arturia BeatStep MIDI 1/raw ...``` is sending to all devices but
```/Arturia BeatStep MIDI 1/note_on ...``` is sending to only a single device as it should.

Best wishes,
/PLu

**Comment by llloret** [comment]
Hi, @PLu55, can you try with the latest version?
I have tried to reproduce it on my Windows box and it is working just fine. raw messages are sent to just the indicated device.

What OS are you using?

**Comment by llloret** [comment]
Can't replicate and got no feedback. Will reopen if I get more information.
