### ISSUE TITLE
Virtual MIDI port enhancements

### ISSUE THREAD

**Issue by llloret** [llloret/osmid#8]
- [x] MIDI port should only be compiled on Mac and Linux.
- [x] Add the possibility of assigning a name to the Virtual Port (add to -v parameter)

**Comment by samaaron** [comment]
Double thumbs up for the ability to assign a name to the Virtual Port 👍 👍

**Comment by llloret** [comment]
Hi, @samaaron, wish granted! ;)

Just add the name of the virtual port after the -v parameter.
